# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileNameSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(439, 150)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_filename = QtWidgets.QLabel(Dialog)
        self.label_filename.setObjectName("label_filename")
        self.horizontalLayout.addWidget(self.label_filename)
        self.lineEdit_filename = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.horizontalLayout.addWidget(self.lineEdit_filename)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_path = QtWidgets.QLabel(Dialog)
        self.label_path.setObjectName("label_path")
        self.horizontalLayout_3.addWidget(self.label_path)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_btm = QtWidgets.QHBoxLayout()
        self.horizontalLayout_btm.setObjectName("horizontalLayout_btm")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_btm.addItem(spacerItem)
        self.pushButton_save = QtWidgets.QPushButton(Dialog)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_btm.addWidget(self.pushButton_save)
        self.horizontalLayout_btm.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_btm)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_filename.setText(_translate("Dialog", "Mesh filename: "))
        self.label.setText(_translate("Dialog", "File will be saved at "))
        self.label_path.setText(_translate("Dialog", "..."))
        self.pushButton_save.setText(_translate("Dialog", "Save"))
