# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadingWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadingWin(object):
    def setupUi(self, LoadingWin):
        LoadingWin.setObjectName("LoadingWin")
        LoadingWin.setWindowModality(QtCore.Qt.ApplicationModal)
        LoadingWin.resize(261, 116)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LoadingWin)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(LoadingWin)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(LoadingWin)
        QtCore.QMetaObject.connectSlotsByName(LoadingWin)

    def retranslateUi(self, LoadingWin):
        _translate = QtCore.QCoreApplication.translate
        LoadingWin.setWindowTitle(_translate("LoadingWin", "Dialog"))
