# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewProj.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(571, 351)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.LineEdit_ProjName = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_ProjName.sizePolicy().hasHeightForWidth())
        self.LineEdit_ProjName.setSizePolicy(sizePolicy)
        self.LineEdit_ProjName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LineEdit_ProjName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LineEdit_ProjName.setObjectName("LineEdit_ProjName")
        self.horizontalLayout.addWidget(self.LineEdit_ProjName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.LineEdit_ProjDir = QtWidgets.QLineEdit(Dialog)
        self.LineEdit_ProjDir.setObjectName("LineEdit_ProjDir")
        self.horizontalLayout_2.addWidget(self.LineEdit_ProjDir)
        self.pushButton_browser = QtWidgets.QPushButton(Dialog)
        self.pushButton_browser.setObjectName("pushButton_browser")
        self.horizontalLayout_2.addWidget(self.pushButton_browser)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.TextEdit_Description = QtWidgets.QTextEdit(Dialog)
        self.TextEdit_Description.setObjectName("TextEdit_Description")
        self.verticalLayout.addWidget(self.TextEdit_Description)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_create = QtWidgets.QPushButton(Dialog)
        self.pushButton_create.setObjectName("pushButton_create")
        self.horizontalLayout_3.addWidget(self.pushButton_create)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.LineEdit_ProjName, self.LineEdit_ProjDir)
        Dialog.setTabOrder(self.LineEdit_ProjDir, self.pushButton_browser)
        Dialog.setTabOrder(self.pushButton_browser, self.TextEdit_Description)
        Dialog.setTabOrder(self.TextEdit_Description, self.pushButton_create)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New Project"))
        self.label.setText(_translate("Dialog", "Project name:"))
        self.label_2.setText(_translate("Dialog", "Project directory:"))
        self.pushButton_browser.setText(_translate("Dialog", "..."))
        self.label_3.setText(_translate("Dialog", "Description:"))
        self.pushButton_create.setText(_translate("Dialog", "Create"))
