# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectWin(object):
    def setupUi(self, SelectWin):
        SelectWin.setObjectName("SelectWin")
        SelectWin.resize(331, 298)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        SelectWin.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectWin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SelectWin)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(SelectWin)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_ok = QtWidgets.QPushButton(SelectWin)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SelectWin)
        QtCore.QMetaObject.connectSlotsByName(SelectWin)

    def retranslateUi(self, SelectWin):
        _translate = QtCore.QCoreApplication.translate
        SelectWin.setWindowTitle(_translate("SelectWin", "Select mesh"))
        self.label.setText(_translate("SelectWin", "Select mesh to display"))
        self.pushButton_ok.setText(_translate("SelectWin", "OK"))
