# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabXYZtable.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_xyz_table(object):
    def setupUi(self, xyz_table):
        xyz_table.setObjectName("xyz_table")
        xyz_table.resize(304, 416)
        self.verticalLayout = QtWidgets.QVBoxLayout(xyz_table)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(xyz_table)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(xyz_table)
        QtCore.QMetaObject.connectSlotsByName(xyz_table)

    def retranslateUi(self, xyz_table):
        _translate = QtCore.QCoreApplication.translate
        xyz_table.setWindowTitle(_translate("xyz_table", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("xyz_table", "X"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("xyz_table", "Y"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("xyz_table", "Z"))
